/**
 * store/fixtures — builders for run directories.
 *
 * These exist so a test can produce a *real* run directory in three lines instead of hand-writing
 * a `RunMeta`, and so the golden diff fixtures (spec §11.3) are generated by the same writer the
 * runner uses — a fixture that drifts from the real layout tests nothing.
 *
 * Everything here is deterministic: fixed timestamps, fixed env, no randomness.
 */

import { PNG } from 'pngjs';

import { SCENARIO_NONE, STYLE_PROPS } from '../types.js';
import { beginRun, type RunMetaInput } from './run-store.js';
import { SOURCE_E2E, SOURCE_REPLAY, UNKNOWN_REVISION } from './internal/e2e.js';
import type { E2eRunInfo, MaybeE2e } from './internal/e2e.js';
import { sha256 } from './internal/hash.js';
import { VARIANT_NONE, type MaybeVariant } from './internal/variant.js';
import type {
  A11ySnapshot,
  ConsoleEntry,
  DomNode,
  DomSnapshot,
  FlowSnapshot,
  NetworkEntry,
  RunEnv,
  RunId,
  RunMeta,
  Step,
  StepResult,
  StyleProp,
  StyleSubset,
  ViewportId,
} from '../types.js';

export const FIXED_START = '2026-08-08T10:00:00.000Z';
export const FIXED_END = '2026-08-08T10:00:41.000Z';

export function makeStyles(overrides: Partial<StyleSubset> = {}): StyleSubset {
  const base = {} as Record<StyleProp, string>;
  for (const prop of STYLE_PROPS) base[prop] = '';
  return { ...base, ...overrides };
}

export function makeEnv(overrides: Partial<RunEnv> = {}): RunEnv {
  return {
    tool: '0.1.0',
    node: 'v20.0.0',
    playwright: '1.50.0',
    chromium: '133.0.0',
    os: 'darwin-arm64',
    deviceScaleFactor: 2,
    ...overrides,
  };
}

export function makeDomNode(overrides: Partial<DomNode> = {}): DomNode {
  return {
    path: 'html>body',
    parent: null,
    depth: 1,
    tag: 'body',
    rect: { x: 0, y: 0, w: 1280, h: 800 },
    visible: true,
    styles: makeStyles(),
    attrs: {},
    ...overrides,
  };
}

export function makeDomSnapshot(
  step: string,
  viewport: ViewportId,
  nodes: DomNode[] = [makeDomNode()],
  overrides: Partial<DomSnapshot> = {},
): DomSnapshot {
  return {
    step,
    viewport,
    url: 'http://localhost:5173/',
    capturedAt: FIXED_START,
    deviceScaleFactor: 2,
    document: { w: 1280, h: 800 },
    nodeCount: nodes.length,
    truncated: false,
    masks: [],
    nodes,
    ...overrides,
  };
}

export function makeA11ySnapshot(step: string, viewport: ViewportId): A11ySnapshot {
  return { step, viewport, root: { role: 'WebArea', name: 'fixture' } };
}

export function makeStepResult(
  id: string,
  index: number,
  overrides: Partial<StepResult> = {},
): StepResult {
  return {
    id,
    index,
    status: 'ok',
    shoot: true,
    startedAt: FIXED_START,
    finishedAt: FIXED_END,
    durationMs: 41_000,
    viewports: {},
    truncated: false,
    consoleErrors: 0,
    networkRequests: 0,
    harMisses: 0,
    ...overrides,
  };
}

export function makeFlowSnapshot(flow: string, steps: Step[], viewports: ViewportId[]): FlowSnapshot {
  return {
    version: 1,
    flow,
    baseUrl: 'http://localhost:5173',
    viewports,
    network: { mode: 'off' },
    steps,
  };
}

export function makeRunMeta(
  flow: string,
  overrides: Partial<RunMeta> & MaybeVariant & MaybeE2e = {},
): RunMetaInput {
  const base: RunMetaInput = {
    flow,
    /** Overridable, but a fixture with no scenario is the slice-1 case: the reserved `none` (§6). */
    scenario: SCENARIO_NONE,
    /** Likewise: a fixture that says nothing about variants captured the unmodified page (§5). */
    variant: VARIANT_NONE,
    /** And a fixture that says nothing about its source is a replay, as every pre-e2e run is. */
    source: SOURCE_REPLAY,
    flowHash: sha256(flow),
    revision: { sha: '9f8e7d6', ref: 'main', dirty: false },
    mode: 'attach',
    network: 'off',
    harHits: 0,
    harMisses: 0,
    viewports: ['1280x800'],
    status: 'ok',
    failedSteps: [],
    env: makeEnv(),
    startedAt: FIXED_START,
    finishedAt: FIXED_END,
    unstable: false,
    pinned: false,
    pruned: false,
    warnings: [],
  };
  return { ...base, ...overrides };
}

/**
 * An ingested run (e2e spec §7): source `e2e`, an e2e block carrying the identity the ingest is
 * keyed by, and `revision: unknown` — which is what a trace really yields, since no Playwright
 * trace archive carries git metadata at any format version.
 */
export function makeE2eRunMeta(
  flow: string,
  e2e: Partial<E2eRunInfo> = {},
  overrides: Partial<RunMeta> & MaybeE2e = {},
): RunMetaInput {
  const title = e2e.testTitle ?? `${flow}.spec.ts:12 \u203A ${flow} \u203A ingested`;
  return makeRunMeta(flow, {
    source: SOURCE_E2E,
    revision: UNKNOWN_REVISION,
    e2e: {
      traceHash: sha256(`${flow}:${title}`),
      testTitle: title,
      titleKey: `${flow}.spec.ts \u203A ${flow} \u203A ingested`,
      ...e2e,
    },
    ...overrides,
  });
}

/** A 1x1 PNG. Small, valid, and byte-stable — enough for path and retention tests. */
export const TINY_PNG = Uint8Array.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
  0x89, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
  0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae,
  0x42, 0x60, 0x82,
]);

/**
 * A solid-colour PNG of a given size.
 *
 * {@link TINY_PNG} is 1x1, which is enough for path and retention tests and useless for diff ones:
 * the engine drops any region below `minRegionArea` (64 px² by default), so two different 1x1 images
 * produce a pair with no findings at all. A fixture that wants a *real* finding needs real pixels.
 */
export function solidPng(
  width: number,
  height: number,
  [red, green, blue]: readonly [number, number, number],
): Uint8Array {
  const png = new PNG({ width, height });
  for (let offset = 0; offset < png.data.length; offset += 4) {
    png.data[offset] = red;
    png.data[offset + 1] = green;
    png.data[offset + 2] = blue;
    png.data[offset + 3] = 255;
  }
  return Uint8Array.from(PNG.sync.write(png));
}

export interface FixtureStep {
  id: string;
  /** Defaults to every viewport of the run. Pass `[]` for a step that produced no shot. */
  viewports?: ViewportId[];
  nodes?: DomNode[];
  /** Defaults to {@link TINY_PNG}. Pass {@link solidPng} output for a fixture the diff engine sees. */
  screenshot?: Uint8Array;
  /** Dimensions recorded on the shot. Default 1x1, matching {@link TINY_PNG}. */
  size?: { width: number; height: number };
  result?: Partial<StepResult>;
  console?: ConsoleEntry[];
  network?: NetworkEntry[];
}

export interface WriteFixtureRunOptions {
  root: string;
  flow: string;
  steps: FixtureStep[];
  viewports?: ViewportId[];
  meta?: Partial<RunMeta> & MaybeVariant & MaybeE2e;
}

/** Build and commit a complete run directory through the real writer. */
export async function writeFixtureRun(
  options: WriteFixtureRunOptions,
): Promise<{ runId: RunId; runDir: string; meta: RunMeta }> {
  const viewports = options.viewports ?? ['1280x800'];
  const draft = await beginRun(options.root, options.flow);

  const specSteps: Step[] = options.steps.map((step) => ({ id: step.id, shoot: true }));
  await draft.writeFlowSnapshot(makeFlowSnapshot(options.flow, specSteps, viewports));

  for (const [index, step] of options.steps.entries()) {
    const stepViewports = step.viewports ?? viewports;
    const result = makeStepResult(step.id, index, step.result);
    for (const viewport of stepViewports) {
      const dom = makeDomSnapshot(step.id, viewport, step.nodes ?? [makeDomNode()]);
      result.viewports[viewport] = await draft.writeShot(step.id, {
        viewport,
        screenshot: step.screenshot ?? TINY_PNG,
        dom,
        a11y: makeA11ySnapshot(step.id, viewport),
        width: step.size?.width ?? 1,
        height: step.size?.height ?? 1,
      });
    }
    await draft.writeStepResult(result);
    await draft.writeStepConsole(step.id, step.console ?? []);
    await draft.writeStepNetwork(step.id, step.network ?? []);
  }

  return draft.commit(makeRunMeta(options.flow, { viewports, ...options.meta }));
}
