/**
 * store/fixtures — builders for run directories.
 *
 * These exist so a test can produce a *real* run directory in three lines instead of hand-writing
 * a `RunMeta`, and so the golden diff fixtures (spec §11.3) are generated by the same writer the
 * runner uses — a fixture that drifts from the real layout tests nothing.
 *
 * Everything here is deterministic: fixed timestamps, fixed env, no randomness.
 */

import { STYLE_PROPS } from '../types.js';
import { beginRun, type RunMetaInput } from './run-store.js';
import { sha256 } from './internal/hash.js';
import type {
  A11ySnapshot,
  ConsoleEntry,
  DomNode,
  DomSnapshot,
  FlowSnapshot,
  NetworkEntry,
  RunEnv,
  RunId,
  RunMeta,
  Step,
  StepResult,
  StyleProp,
  StyleSubset,
  ViewportId,
} from '../types.js';

export const FIXED_START = '2026-08-08T10:00:00.000Z';
export const FIXED_END = '2026-08-08T10:00:41.000Z';

export function makeStyles(overrides: Partial<StyleSubset> = {}): StyleSubset {
  const base = {} as Record<StyleProp, string>;
  for (const prop of STYLE_PROPS) base[prop] = '';
  return { ...base, ...overrides };
}

export function makeEnv(overrides: Partial<RunEnv> = {}): RunEnv {
  return {
    tool: '0.1.0',
    node: 'v20.0.0',
    playwright: '1.50.0',
    chromium: '133.0.0',
    os: 'darwin-arm64',
    deviceScaleFactor: 2,
    ...overrides,
  };
}

export function makeDomNode(overrides: Partial<DomNode> = {}): DomNode {
  return {
    path: 'html>body',
    parent: null,
    depth: 1,
    tag: 'body',
    rect: { x: 0, y: 0, w: 1280, h: 800 },
    visible: true,
    styles: makeStyles(),
    attrs: {},
    ...overrides,
  };
}

export function makeDomSnapshot(
  step: string,
  viewport: ViewportId,
  nodes: DomNode[] = [makeDomNode()],
  overrides: Partial<DomSnapshot> = {},
): DomSnapshot {
  return {
    step,
    viewport,
    url: 'http://localhost:5173/',
    capturedAt: FIXED_START,
    deviceScaleFactor: 2,
    document: { w: 1280, h: 800 },
    nodeCount: nodes.length,
    truncated: false,
    masks: [],
    nodes,
    ...overrides,
  };
}

export function makeA11ySnapshot(step: string, viewport: ViewportId): A11ySnapshot {
  return { step, viewport, root: { role: 'WebArea', name: 'fixture' } };
}

export function makeStepResult(
  id: string,
  index: number,
  overrides: Partial<StepResult> = {},
): StepResult {
  return {
    id,
    index,
    status: 'ok',
    shoot: true,
    startedAt: FIXED_START,
    finishedAt: FIXED_END,
    durationMs: 41_000,
    viewports: {},
    truncated: false,
    consoleErrors: 0,
    networkRequests: 0,
    harMisses: 0,
    ...overrides,
  };
}

export function makeFlowSnapshot(flow: string, steps: Step[], viewports: ViewportId[]): FlowSnapshot {
  return {
    version: 1,
    flow,
    baseUrl: 'http://localhost:5173',
    viewports,
    network: { mode: 'off' },
    steps,
  };
}

export function makeRunMeta(flow: string, overrides: Partial<RunMeta> = {}): RunMetaInput {
  const base: RunMetaInput = {
    flow,
    flowHash: sha256(flow),
    revision: { sha: '9f8e7d6', ref: 'main', dirty: false },
    mode: 'attach',
    network: 'off',
    harHits: 0,
    harMisses: 0,
    viewports: ['1280x800'],
    status: 'ok',
    failedSteps: [],
    env: makeEnv(),
    startedAt: FIXED_START,
    finishedAt: FIXED_END,
    unstable: false,
    pinned: false,
    pruned: false,
    warnings: [],
  };
  return { ...base, ...overrides };
}

/** A 1x1 PNG. Small, valid, and byte-stable — enough for path and retention tests. */
export const TINY_PNG = Uint8Array.from([
  0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
  0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x06, 0x00, 0x00, 0x00, 0x1f, 0x15, 0xc4,
  0x89, 0x00, 0x00, 0x00, 0x0a, 0x49, 0x44, 0x41, 0x54, 0x78, 0x9c, 0x63, 0x00, 0x01, 0x00, 0x00,
  0x05, 0x00, 0x01, 0x0d, 0x0a, 0x2d, 0xb4, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44, 0xae,
  0x42, 0x60, 0x82,
]);

export interface FixtureStep {
  id: string;
  /** Defaults to every viewport of the run. Pass `[]` for a step that produced no shot. */
  viewports?: ViewportId[];
  nodes?: DomNode[];
  result?: Partial<StepResult>;
  console?: ConsoleEntry[];
  network?: NetworkEntry[];
}

export interface WriteFixtureRunOptions {
  root: string;
  flow: string;
  steps: FixtureStep[];
  viewports?: ViewportId[];
  meta?: Partial<RunMeta>;
}

/** Build and commit a complete run directory through the real writer. */
export async function writeFixtureRun(
  options: WriteFixtureRunOptions,
): Promise<{ runId: RunId; runDir: string; meta: RunMeta }> {
  const viewports = options.viewports ?? ['1280x800'];
  const draft = await beginRun(options.root, options.flow);

  const specSteps: Step[] = options.steps.map((step) => ({ id: step.id, shoot: true }));
  await draft.writeFlowSnapshot(makeFlowSnapshot(options.flow, specSteps, viewports));

  for (const [index, step] of options.steps.entries()) {
    const stepViewports = step.viewports ?? viewports;
    const result = makeStepResult(step.id, index, step.result);
    for (const viewport of stepViewports) {
      const dom = makeDomSnapshot(step.id, viewport, step.nodes ?? [makeDomNode()]);
      result.viewports[viewport] = await draft.writeShot(step.id, {
        viewport,
        screenshot: TINY_PNG,
        dom,
        a11y: makeA11ySnapshot(step.id, viewport),
        width: 1,
        height: 1,
      });
    }
    await draft.writeStepResult(result);
    await draft.writeStepConsole(step.id, step.console ?? []);
    await draft.writeStepNetwork(step.id, step.network ?? []);
  }

  return draft.commit(makeRunMeta(options.flow, { viewports, ...options.meta }));
}
