/**
 * diff/e2e-noise — the noise-tolerant diff settings an ingested pair is diffed under (e2e spec §5,
 * D27), in one place so they are tunable configuration rather than folklore.
 *
 * ## Why a separate set of settings at all
 *
 * An e2e capture has no frozen clock, no seeded RNG, no disabled animations and no settle gate: the
 * suite drives the browser and none of the runner's knobs apply (spec §2, §5). Putting those runs
 * through the replay thresholds would greet a first-time user with a wall of findings generated by
 * animation frames and clock text, and the credibility of a diffing tool is set entirely by its
 * false-positive rate (D27).
 *
 * ## What the two knobs are — and why there are two, not the three §5 tabulates
 *
 * §5's table lists *pixel threshold*, *minimum region area* and *antialias tolerance*. The engine
 * has two controls, not three: `pixelmatch` exposes a single YIQ colour-delta `threshold`, which
 * doubles as its antialias sensitivity, and `pixel.ts` already surfaces it under the spec's own
 * name `antialiasTolerance` (with `includeAA: false`). §5's first two rows are therefore one knob
 * here. A third setting is deliberately *not* invented: the only shape it could take — a floor on a
 * shot's changed-pixel ratio — would hide small real changes, since one changed word on an 798×532
 * trace frame is roughly 0.2% of it, well under any ratio worth calling a floor.
 *
 * ## What was measured, and what was merely chosen
 *
 * D27 says these values are provisional, and §10 proposes calibrating them against the fixture
 * suite's own noise floor. That plan does not work, and the measurements are recorded here so the
 * next person does not repeat it. Against real archives produced by the repo's own playwright-core
 * (chromium 151), two runs of a hermetic page:
 *
 * - **produce byte-identical JPEGs for a given rendered state** — sha1 match, and 0.0000% pixel
 *   difference on every corresponding frame. The hermetic pixel-noise floor is *zero*, so it
 *   calibrates nothing;
 * - **produce a different number of frames** (7 versus 6, the extra one a leading blank
 *   `about:blank` composite). Pairing those by position gives 0.04%–0.97% of the frame changed, and
 *   raising the colour threshold sixfold (0.1 → 0.6) only takes the worst case from 0.97% to 0.59%.
 *   **E2E noise on a hermetic app is alignment noise, and no threshold fixes it.**
 * - **survive a lossy round trip at the replay threshold**: re-encoding a trace frame at JPEG q90
 *   moves 7.4%–8.3% of its pixels (max channel delta 13–33, mean 1.4–1.7 on the pixels it touches)
 *   and yields *zero* pixelmatch-changed pixels at `antialiasTolerance: 0.1`. The codec alone does
 *   not require a raised threshold.
 *
 * So the values below are **chosen, not measured**, and are aimed at the failure the fixture cannot
 * exhibit: a real suite's clocks, animations and network jitter. The honest remedy for the two
 * failures that *were* measured is elsewhere — `e2e-map.yaml`'s `ignore` list for clocks and
 * animated regions (§5), and step→shot mapping for alignment (§4 of the ingestion work).
 */

import type { DiffEngineOptions } from '../types.js';
import { isE2eRun } from '../store/internal/e2e.js';
import type { MaybeE2e } from '../store/internal/e2e.js';

/** The settings an e2e pair is diffed under, once defaults and overrides have been merged. */
export interface E2eNoiseSettings {
  minRegionArea: number;
  antialiasTolerance: number;
}

/**
 * The e2e defaults. One definition, referenced by config, the engine and the docs.
 *
 * `antialiasTolerance` 0.1 → **0.25**. The replay default already absorbs a full q90 round trip of
 * the fixture's flat synthetic content (measured above), so this margin is for the gradients,
 * photographic content and subpixel text a real application has and the fixture does not. It is the
 * value most likely to move once a real suite is available.
 *
 * `minRegionArea` 64 → **256**: one doubling in each linear dimension, an 8×8 image-space box
 * becoming 16×16. The arithmetic in CSS pixels is worth stating, because the two capture paths do
 * not agree on scale. A replay shot is a PNG at `deviceScaleFactor` 2, so 64 image px² is 16 CSS
 * px². A trace frame is downscaled to fit an 800×800 box with the device scale factor discarded
 * (measured: a 900×600 viewport is delivered at 798×532, 0.887 image px per CSS px), so 256 image
 * px² is about 326 CSS px² — an 18×18 CSS box. That is a real cost, and it is the point: below that
 * size, an ingested pair cannot tell a moved caret from a regression.
 */
export const E2E_DIFF_DEFAULTS: E2eNoiseSettings = {
  minRegionArea: 256,
  antialiasTolerance: 0.25,
};

/**
 * The `e2e:` block of `diff:` config (spec §5, "overridable per project"), plus the `ignore` list
 * `e2e-map.yaml` contributes — clocks and animated regions, "which no amount of threshold tuning
 * handles correctly".
 *
 * Every field is optional: an absent one takes the documented default, and an unreadable one takes
 * the default *and says so*, because a threshold silently ignored is a threshold the user believes
 * is in force.
 */
export interface E2eNoiseOverrides {
  minRegionArea?: number;
  antialiasTolerance?: number;
  /** Selectors ignored on ingested pairs only, appended to `diff.ignore`. */
  ignore?: readonly string[];
}

/**
 * `DiffEngineOptions` with the `e2e:` block.
 *
 * Structural, exactly as `PairVariants` is: `src/types.ts` does not yet carry the block, and every
 * caller that only knows `DiffEngineOptions` keeps working because it is additive.
 */
export type E2eAwareDiffOptions = DiffEngineOptions & { e2e?: E2eNoiseOverrides };

function invalid(field: string, value: unknown, requirement: string, fallback: number): string {
  return (
    `e2e.${field} must be ${requirement}, got ${JSON.stringify(value)} — ` +
    `using the default ${fallback}`
  );
}

/**
 * Defaults merged with the project's `e2e:` overrides, plus a warning for each override that could
 * not be used. Pure, and independent of any pair, so config tests can assert it directly.
 */
export function e2eNoiseSettings(overrides: E2eNoiseOverrides | undefined): {
  settings: E2eNoiseSettings;
  warnings: string[];
} {
  const settings: E2eNoiseSettings = { ...E2E_DIFF_DEFAULTS };
  const warnings: string[] = [];
  if (overrides === undefined) return { settings, warnings };

  const { minRegionArea, antialiasTolerance } = overrides;
  if (minRegionArea !== undefined) {
    if (typeof minRegionArea === 'number' && Number.isInteger(minRegionArea) && minRegionArea >= 0) {
      settings.minRegionArea = minRegionArea;
    } else {
      warnings.push(
        invalid(
          'minRegionArea',
          minRegionArea,
          'a non-negative integer',
          E2E_DIFF_DEFAULTS.minRegionArea,
        ),
      );
    }
  }
  if (antialiasTolerance !== undefined) {
    if (
      typeof antialiasTolerance === 'number' &&
      Number.isFinite(antialiasTolerance) &&
      antialiasTolerance >= 0 &&
      antialiasTolerance <= 1
    ) {
      settings.antialiasTolerance = antialiasTolerance;
    } else {
      warnings.push(
        invalid(
          'antialiasTolerance',
          antialiasTolerance,
          'a number between 0 and 1',
          E2E_DIFF_DEFAULTS.antialiasTolerance,
        ),
      );
    }
  }
  return { settings, warnings };
}

/** What {@link resolveDiffOptions} decided, and why, for the caller that has to record it. */
export interface ResolvedDiffOptions {
  /** The options the engine runs with. **Identical by reference** for a replay-only pair. */
  options: DiffEngineOptions;
  /** Whether the e2e settings were applied — true when either side was ingested. */
  e2e: boolean;
  /** Unusable `e2e:` overrides, for `DiffResult.warnings`. Empty unless config is wrong. */
  warnings: string[];
}

/**
 * The options this pair is diffed under (§5, D27).
 *
 * Two properties this function is built around:
 *
 * 1. **A replay-only pair is untouched, by reference.** E2E mode is opt-in and "nothing about
 *    `vdiff run` changes" (§1), which has to include the diff of two replay runs producing byte-
 *    identical output — and the same cache key — as it did before this slice existed.
 * 2. **Resolving twice is resolving once.** `computeDiff` resolves to build the cache key and
 *    `diffRuns` resolves to run the stages, on the same inputs; the `ignore` merge therefore
 *    appends only selectors the base list does not already carry, so no path can double the list
 *    (which `ignoreSelectorWarnings` would otherwise report twice, from one config entry).
 *
 * The settings apply to a *pair*, not to a run: a cross-source pair is diffed under the e2e
 * settings, because the noisier side sets what the comparison can resolve.
 */
export function resolveDiffOptions(
  options: E2eAwareDiffOptions,
  base: MaybeE2e | null | undefined,
  head: MaybeE2e | null | undefined,
): ResolvedDiffOptions {
  if (!isE2eRun(base) && !isE2eRun(head)) {
    return { options, e2e: false, warnings: [] };
  }

  const { settings, warnings } = e2eNoiseSettings(options.e2e);
  const extra = (options.e2e?.ignore ?? []).filter((selector) => !options.ignore.includes(selector));

  return {
    options: {
      ...options,
      minRegionArea: settings.minRegionArea,
      antialiasTolerance: settings.antialiasTolerance,
      ignore: extra.length === 0 ? options.ignore : [...options.ignore, ...extra],
    },
    e2e: true,
    warnings,
  };
}
